name: CICD for Nodejs Application with Docker
run-name: ${{ github.actor }} is running CICD for Nodejs Application with Docker

on:
    push:
        branches: [ main, "*"]

jobs:
    unit-testing:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository code
              uses: actions/checkout@v3
            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                node-version: 18
            - name: Install dependencies
              run: npm ci
            - name: Run the unit tests
              run: npm run test
    docker-build-and-test:
        runs-on: ubuntu-latest
        needs: unit-testing
        services:
            docker:
                image: docker:stable
                options: --privileged
        steps:
            - name: Checkout repository code
              uses: actions/checkout@v3
            - name: Build the Docker image
              run: docker build -t nodejs-app .
            - name: Run the docker image to test
              run: docker run -d -p 8080:8080 nodejs-app
            - name: Run the unit tests
              run: npm run test
